[GlobalBadges] Fix 'View Source Code' button to make it actually open the URL
HypedDomi/Enmity-Stuff pull request #1
Opened 2024-03-12 17:07 UTC by byeoon

Previously, the button would do nothing and clicking it would do nothing.  I updated it so now properly opens the correct link and functions as expected. I also improved a couple lines of text in settings to make it sound better.

2024-03-12 20:39 UTC, domi-btnr requested changes

2024-03-12 20:39 UTC, domi-btnr commented on GlobalBadges/manifest.json
> +    "version": "1.2.6.1",
Versions like that will not work with my Updater. Could you change it back to `1.2.6` or bump it to `1.2.7`

2024-03-12 20:39 UTC, domi-btnr commented on GlobalBadges/src/components/Settings.tsx
> +                        subLabel={"Checks automatically for updates when starting GlobalBadges"}
Instead of hard coding the name, use `${name}` which is the name from the manifest

2024-03-12 20:39 UTC, domi-btnr commented
And please don't add the build plugins from the `dist` folder

2024-03-13 02:15 UTC, byeoon commented
I have no idea what I did, but the codespace(s - yes I tried using two) that I was using to push these commits just stopped working entirely, and corrupted my work and progress. Tomorrow morning I'll update everything with the reviewed changes and fix everything.

2024-03-13 15:13 UTC, byeoon commented
These changes should be fixed now, and I also built it for production

2024-03-13 15:16 UTC, domi-btnr approved these changes
I'll remove the Build files, since I build the plugins with the Workflow and will also update the other Plugins to fix this. Thank you :3

2024-03-13 15:16 UTC, domi-btnr commented on GlobalBadges/manifest.json
> +    "hash": "f361d9535ed13801a75ce513dfbfa0652a18cd70"
Please don't build the files by yourself. I have a workflow for this

2024-03-13 15:24 UTC, merged